# Generated by Django 3.0.7 on 2020-06-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_point_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='user',
            name='month',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
