# Generated by Django 3.0.7 on 2020-06-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200605_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='point',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
